module-lwe/src/lib.rs, ring-lwe/src/lib.rs
- we default to more secure parameters
- one can choose less secure parameters optionally
=> change default params for RLWE and MLWE

.github/workflows/basic.yml, module-lwe/src/encrypt.rs, module-lwe/src/keygen.rs, module-lwe/src/lib.rs, module-lwe/src/main.rs, module-lwe/src/ring_mod.rs, module-lwe/src/test.rs, ring-lwe/src/encrypt.rs, ring-lwe/src/keygen.rs, ring-lwe/src/lib.rs, ring-lwe/src/main.rs, ring-lwe/src/test.rs
- more control over random number generation
- choose seed as Some(seed) or None
- uses StdRng::from_entropy() as default
=> set optional random seed for ring-lwe and module-lwe

README.md
display the MIT license badge in markdown on the README
=> add MIT license badge to README

ring-lwe/src/lib.rs, ring-lwe/src/test.rs
- extra line with params causing warning
- nearest int can be computed using integer division
=> remove extra default params, fix nearest_int

ring-lwe/src/lib.rs
appears n=16 is necessary for tests to pass
=> set parameters which guarantee all tests pass

src/decrypt.rs, src/encrypt.rs, src/keygen.rs, src/lib.rs, src/test.rs
This fixes the flaky and failing homomorphic product test dec(enc(2)*enc(3)) == 6. 
The issue was primarily with how random polynomials are generated. This differs greatly from Sage to Rust. In Sage, the coefficients essentially come from ZZ.random_element() which gives {-1,0,+1} with probability ~1/5. This is coincidentally about what you need for a notion of "small" as described in [Stange's notes](https://math.colorado.edu/~kstange/teaching-resources/crypto/RingLWE-notes.pdf), where ternary polynomials are used. Sage also does arithmetic and holds coefficients in ZZ, even in quotient rings like Z_q[x]/(x^n+1). 
One could also use a normal distribution with some std. deviation sigma centered around zero, which also gives a "small" polynomial, however there is the potential for large …
=> Fix homomorphic product test

src/keygen.rs
the choice of which distribution to use to randomly generate the polynomial `a` is sensitive. while using a ternary polynomial works, it may not be secure. ideally we would use a polynomial generated from a uniform distribution on [0,q-1], but that seems to break the tests.
=> use normal poly for a

src/encrypt.rs, src/keygen.rs
changed keygen and encrypt computations to be done mod q^2, so that homomorphic product would work with uniformly chosen a.
=> work mod q^2 to allow uniform a

src/lib.rs
added polyrem function to lib.rs, so that polynomial long division .division() is no longer necessary
=> remove polynomial long division

src/bin/benchmark.rs, src/test.rs
Add two benchmarking tests, one for small polynomial multiplication and one for polynomials of degree n (default is n=512).
Note that currently:
```
Standard multiplication took: 11.458µs
Fast multiplication took: 19.292µs
Standard multiplication took: 3.399625ms
Fast multiplication took: 10.0545ms
```
So fast multiplication is currently slower than naive multiplication.
=> add benchmarking to measure time for polymul, polymul_fast

src/lib.rs
Using `polyrem` rather than long division in polymul_fast results in a significant speedup. The benchmarks now show:
```
Standard multiplication took: 13.125µs
Fast multiplication took: 42.541µs
Standard multiplication took: 10.607458ms
Fast multiplication took: 2.235958ms
```
=> use polyrem in polymul_fast to improve speed

src/decrypt.rs, src/encrypt.rs, src/lib.rs
encode messages using bits rather than bytes to allow for smaller values of t. currently t=16 is okay with even smaller q=12289. need a separate PR to get t=2 working for all tests.
=> use bitwise encoding vs. bytes

src/bin/benchmark.rs, src/lib.rs, src/test.rs
fixing the nearest_int function allows for `t=2`, but the tests need to be modified since using constants like 2 and 3 which aren't as meaningful mod 2.
this PR modifies the homomorphic addition and product tests to use binary polynomials which work for all values of `t`.
we also remove the prime modulus `p` and just have a single ciphertext modulus `q` which is prime, and if not changes would need to be made to ensure the NTT works.
=> ability to set t=2

Cargo.toml
update version to 0.1.1. in this version we are using polymul_fast for all multiplications, are using `ntt=0.1.4` which allows for the NTT mod q^2, and the `hom_prod_test` has been appropriately updated and is passing.
=> update version to 0.1.1

Cargo.toml
updates the version to 0.1.2. we now use v0.1.8 of `ntt`. root is no longer a parameter, but is computed implicitly by omega. a bug has been resolved for omega when `q=12289` and `n=512`, so now this test case passes. 
now `default-run = ring-lwe`.
=> update to version 0.1.2

src/lib.rs
this function is not used in this crate, but is used in other crates (such as module-lwe). since polyadd has `f` passed by reference, if `f.clone()` is passed to `polysub`, then `&f.clone()` is passed to polyadd.
=> change polysub to pass by ref

Cargo.toml
this changes polysub to have `f` passed by reference for use in `module-lwe`
=> update to version v.0.1.4

src/lib.rs
now manually computes the nearest power of 2 at least twice the max of input degrees+1
=> fix degree computations in polymul_fast

Cargo.toml
reorganizes functions from `lib.rs` into `utils.rs`, publicly exposing all functions.
=> update to v0.1.5

src/utils.rs
suppress warning for polymul. it's used in `cargo test`, but not in `cargo run` since we replaced it with `polymul_fast`
=> suppress warning for polymul

Cargo.toml
adds criterion benchmarking for `keygen`, `encrypt`, `decrypt`, `polymul_fast`
=> update to v0.1.6

Cargo.toml, src/decrypt.rs, src/encrypt.rs, src/keygen.rs
use `base64::{engine::general_purpose, Engine as _}` and `bincode` for base64 encoding of public key, secret key, and ciphertext strings. this is much more efficient than using comma-separated strings of digits, and also avoids commas.
=> Use base64 encoding

Cargo.toml
uses base64 encoding for keys and ciphertext strings
=> update to v0.1.7
